const fatosHistoricos = [
  { "Ano": "1920", "Fato": "As mulheres ganham o direito ao voto no EUA" },
  { "Ano": "1921", "Fato": "Fundação do Partido Comunista Chinês" },
  { "Ano": "1922", "Fato": "Semana de Arte Moderna no Brasil" },
  { "Ano": "1923", "Fato": "Grande terremoto de Kanto devasta Tóquio" },
  { "Ano": "1924", "Fato": "Morte de Lenin na União Soviética" },
  { "Ano": "1925", "Fato": "Primeira transmissão de televisão mecânica" },
  { "Ano": "1926", "Fato": "Primeira demonstração pública de televisão" },
  { "Ano": "1927", "Fato": "Charles Lindbergh atravessa o Atlântico sozinho" },
  { "Ano": "1928", "Fato": "Alexander Fleming descobre a penicilina" },
  { "Ano": "1929", "Fato": "Grande Depressão começa com a quebra da Bolsa de NY" },
  { "Ano": "1930", "Fato": "Revolução de 1930 no Brasil - Getúlio Vargas assume" },
  { "Ano": "1931", "Fato": "Inauguração do Empire State Building" },
  { "Ano": "1932", "Fato": "Revolução Constitucionalista em São Paulo" },
  { "Ano": "1933", "Fato": "Adolf Hitler torna-se chanceler da Alemanha" },
  { "Ano": "1934", "Fato": "Promulgação da segunda Constituição brasileira" },
  { "Ano": "1935", "Fato": "Intentona Comunista no Brasil" },
  { "Ano": "1936", "Fato": "Início da Guerra Civil Espanhola" },
  { "Ano": "1937", "Fato": "Início do Estado Novo no Brasil" },
  { "Ano": "1938", "Fato": "Noite dos Cristais na Alemanha nazista" },
  { "Ano": "1939", "Fato": "Início da Segunda Guerra Mundial" },
  { "Ano": "1940", "Fato": "Batalha da Inglaterra durante a Segunda Guerra" },
  { "Ano": "1941", "Fato": "Ataque japonês a Pearl Harbor" },
  { "Ano": "1942", "Fato": "Brasil declara guerra ao Eixo" },
  { "Ano": "1943", "Fato": "Batalha de Stalingrado - vitória soviética" },
  { "Ano": "1944", "Fato": "Desembarque na Normandia - Dia D" },
  { "Ano": "1945", "Fato": "Fim da Segunda Guerra Mundial" },
  { "Ano": "1946", "Fato": "Promulgação da Constituição democrática no Brasil" },
  { "Ano": "1947", "Fato": "Independência da Índia" },
  { "Ano": "1948", "Fato": "Criação do Estado de Israel" },
  { "Ano": "1949", "Fato": "Fundação da República Popular da China" },
  { "Ano": "1950", "Fato": "Brasil vence a Copa do Mundo (Maracanazo)" },
  { "Ano": "1951", "Fato": "Getúlio Vargas retorna à presidência do Brasil" },
  { "Ano": "1952", "Fato": "Elizabeth II torna-se rainha do Reino Unido" },
  { "Ano": "1953", "Fato": "Descoberta da estrutura do DNA" },
  { "Ano": "1954", "Fato": "Suicídio de Getúlio Vargas" },
  { "Ano": "1955", "Fato": "Rosa Parks e o início do movimento pelos direitos civis" },
  { "Ano": "1956", "Fato": "Juscelino Kubitschek assume a presidência do Brasil" },
  { "Ano": "1957", "Fato": "União Soviética lança o Sputnik 1" },
  { "Ano": "1958", "Fato": "Brasil conquista sua primeira Copa do Mundo" },
  { "Ano": "1959", "Fato": "Revolução Cubana - Fidel Castro assume o poder" },
  { "Ano": "1960", "Fato": "Inauguração de Brasília como capital do Brasil" },
  { "Ano": "1961", "Fato": "Yuri Gagarin é o primeiro homem no espaço" },
  { "Ano": "1962", "Fato": "Brasil bicampeão mundial de futebol" },
  { "Ano": "1963", "Fato": "Assassinato do presidente John F. Kennedy" },
  { "Ano": "1964", "Fato": "Golpe militar no Brasil" },
  { "Ano": "1965", "Fato": "Início da Guerra do Vietnã com tropas americanas" },
  { "Ano": "1966", "Fato": "Revolução Cultural Chinesa" },
  { "Ano": "1967", "Fato": "Primeira transplante de coração humano" },
  { "Ano": "1968", "Fato": "Movimento estudantil de Maio de 68 na França" },
  { "Ano": "1969", "Fato": "Neil Armstrong pisa na Lua" },
  { "Ano": "1970", "Fato": "Brasil tricampeão mundial de futebol" },
  { "Ano": "1971", "Fato": "Criação do microprocessador Intel 4004" },
  { "Ano": "1972", "Fato": "Escândalo Watergate nos EUA" },
  { "Ano": "1973", "Fato": "Crise do petróleo" },
  { "Ano": "1974", "Fato": "Revolução dos Cravos em Portugal" },
  { "Ano": "1975", "Fato": "Fim da Guerra do Vietnã" },
  { "Ano": "1976", "Fato": "Fundação da Apple Computer" },
  { "Ano": "1977", "Fato": "Lançamento do filme Star Wars" },
  { "Ano": "1978", "Fato": "Eleição do Papa João Paulo II" },
  { "Ano": "1979", "Fato": "Revolução Islâmica no Irã" },
  { "Ano": "1980", "Fato": "Início da Guerra Irã-Iraque" },
  { "Ano": "1981", "Fato": "Lançamento do primeiro PC da IBM" },
  { "Ano": "1982", "Fato": "Guerra das Malvinas" },
  { "Ano": "1983", "Fato": "Movimento Diretas Já no Brasil" },
  { "Ano": "1984", "Fato": "Descoberta do vírus HIV" },
  { "Ano": "1985", "Fato": "Fim da ditadura militar no Brasil" },
  { "Ano": "1986", "Fato": "Desastre nuclear de Chernobyl" },
  { "Ano": "1987", "Fato": "Acordo de Montreal sobre a camada de ozônio" },
  { "Ano": "1988", "Fato": "Promulgação da Constituição Cidadã no Brasil" },
  { "Ano": "1989", "Fato": "Queda do Muro de Berlim" },
  { "Ano": "1990", "Fato": "Reunificação da Alemanha" },
  { "Ano": "1991", "Fato": "Dissolução da União Soviética" },
  { "Ano": "1992", "Fato": "Impeachment de Fernando Collor no Brasil" },
  { "Ano": "1993", "Fato": "Criação da União Europeia" },
  { "Ano": "1994", "Fato": "Plano Real estabiliza a economia brasileira" },
  { "Ano": "1995", "Fato": "Criação da Organização Mundial do Comércio" },
  { "Ano": "1996", "Fato": "Clonagem da ovelha Dolly" },
  { "Ano": "1997", "Fato": "Morte da Princesa Diana" },
  { "Ano": "1998", "Fato": "Fundação do Google" },
  { "Ano": "1999", "Fato": "Introdução do Euro como moeda" },
  { "Ano": "2000", "Fato": "Bug do Milênio (Y2K)" },
  { "Ano": "2001", "Fato": "Ataques terroristas de 11 de setembro" },
  { "Ano": "2002", "Fato": "Brasil pentacampeão mundial de futebol" },
  { "Ano": "2003", "Fato": "Lula assume a presidência do Brasil" },
  { "Ano": "2004", "Fato": "Tsunami no Oceano Índico" },
  { "Ano": "2005", "Fato": "Furacão Katrina devasta Nova Orleans" },
  { "Ano": "2006", "Fato": "Lançamento do Twitter" },
  { "Ano": "2007", "Fato": "Lançamento do primeiro iPhone" },
  { "Ano": "2008", "Fato": "Crise financeira global" },
  { "Ano": "2009", "Fato": "Barack Obama torna-se presidente dos EUA" },
  { "Ano": "2010", "Fato": "Terremoto devastador no Haiti" },
  { "Ano": "2011", "Fato": "Primavera Árabe" },
  { "Ano": "2012", "Fato": "Descoberta do Bóson de Higgs" },
  { "Ano": "2013", "Fato": "Manifestações de junho no Brasil" },
  { "Ano": "2014", "Fato": "Copa do Mundo no Brasil" },
  { "Ano": "2015", "Fato": "Acordo de Paris sobre mudanças climáticas" },
  { "Ano": "2016", "Fato": "Impeachment de Dilma Rousseff" },
  { "Ano": "2017", "Fato": "Eclipse solar total atravessa os EUA" },
  { "Ano": "2018", "Fato": "Resgate de meninos presos em caverna na Tailândia" },
  { "Ano": "2019", "Fato": "Incêndio na Catedral de Notre-Dame" },
  { "Ano": "2020", "Fato": "Pandemia de COVID-19" },
  { "Ano": "2021", "Fato": "Invasão do Capitólio dos EUA" },
  { "Ano": "2022", "Fato": "Invasão russa da Ucrânia" }
]

module.exports = { fatosHistoricos };